### PR TITLE
Update source() to not use __dirname

### PR DESCRIPTION
**Pull request by RobLoach**
__dirname represents the path to the current Node.js module (twigjs/src/twig.functions.js), not the currently running Twig script. See the documentation on __dirname for more info:
https://nodejs.org/docs/latest/api/modules.html#modules_dirname

### CODE REVIEW

**Comment by dave-irvine** [comment]
@RobLoach tests please and I'll merge!

**Comment by RobLoach** [comment]
I think the tests are already there. It's inherent across all the existing ones.

**Comment by dave-irvine** [comment]
@RobLoach if there were already tests, surely they would be failing in the cases that your fix fixes?

**Comment by RobLoach** [comment]
@dave-irvine Got it! Needed to do a bit more debugging to accurately demonstrate the issue.

**Pull request merged**
