### PR TITLE
Browser tests for inline includes, using asynchronous loading

### PR DESCRIPTION
**Pull request by plepe**
Currently includes commits from #325, will update as soon as these are merged to master.

Currently async loading for inline includes is not supported.

### CODE REVIEW

**Comment by dave-irvine** [comment]
@plepe If the tests are passing, does that mean the functionality exists? If so we can merge this.

**Comment by plepe** [comment]
If I run the tests, they are not passing. I guess you tried only with nodejs? These tests test async loading within browser context.

**Comment by dave-irvine** [comment]
Ok that means we need a test runner for browser tests. Zombie.js ?

**Comment by plepe** [comment]
I don't know. I just run them within Firefox and other browsers on my desktop. To have some CI method would be advantageous.

**Comment by willrowe** [comment]
I'm going to close this since it is so old. @plepe if you would like to submit another PR with everything updated to reflect the latest release, I'll be glad to review it.

**Pull request closed without merging**
