### PR TITLE
Performance improvements when including templates.

### PR DESCRIPTION
**Pull request by JorgenEvens**
Related to issues discussed in https://github.com/twigjs/twig.js/pull/486#issuecomment-311320349

### CODE REVIEW

**Comment by JorgenEvens** [comment]
@DrParanoia This PR should already be a lot faster, can you check when you have the time?

**Comment by DrParanoia** [comment]
@JorgenEvens Hey there! Well it seems that it got a bit faster, but still ~52.6% slower than the old one :(
By iterating my test templates 100k times and running this test 10 times for each version I've got these numbers:

This PR: ~6539.25ms
1.10.3: ~4284.86 (please note that this is 10.0.3 from Dec 9 2016 not Mar 2 2017 since it seems that there are two 1.10.3 tags)

**Comment by DrParanoia** [comment]
@JorgenEvens So, I guess the problem is too complicated? :D

**Comment by olets** [comment]
@DrParanoia b700e13 (2016-12-09) is _0_.10.3; 661265e (2017-03-02) is _1_.10.3

**Comment by JorgenEvens** [comment]
@DrParanoia sorry for the absence, haven't had much time the last two weeks to have another look. It will probably be another week before I am able to have another look.

**Comment by DrParanoia** [comment]
@JorgenEvens No problem m8! Take your time ;)

**Comment by DrParanoia** [comment]
So, will these changes be merged soon? :D

**Comment by JorgenEvens** [comment]
@DrParanoia Does this fully address your performance issues?

https://github.com/twigjs/twig.js/pull/492/commits/aee37a3ad9058f8eae5aa8feb9e3f3f42b9ed1f6 is probably slightly controversial as it is a quick and dirty variation on https://github.com/twigjs/twig.js/pull/439, the current ChildContext implementation however is a HUGE performance bottleneck.

**Comment by DrParanoia** [comment]
@JorgenEvens Well it's a lot better than before! Still, if you know you can do more, please take your time ;) I'm not in a rush to update. Also I re-factored my code to use Web workers for twig rendering, so there are a lot less UI freezes caused by Twig itself.

**Comment by JorgenEvens** [comment]
@dave-irvine what's your stance on the change in https://github.com/twigjs/twig.js/commit/aee37a3ad9058f8eae5aa8feb9e3f3f42b9ed1f6 ( or https://github.com/twigjs/twig.js/pull/439 ) these days?

The `ChildContext` turns out to be a huge performance bottleneck, and I don't see any real advantages of the current implementation over a `Twig.lib.copy`.

**Comment by dave-irvine** [comment]
@JorgenEvens If you've been using it with your changes, the tests pass, and you haven't seen any differences other than a speedup, I can't see any reason not to merge.

If you're all finished let me know and I'll merge it in.

**Comment by JorgenEvens** [comment]
@DrParanoia Here are the numbers I'm getting on the current branch versus the pre-async code. could you verify these?

Could you also verify that I didn't break anything? We don't use `include` much in our templates, so I'm purely relying on some testcases and the unit tests.

**This PR**
```sh
> local/twig.js   chore/include-performance  i=10; while [ $i -gt 0 ]; do node benchmark/test-07.js; i=$((i-1)); done
twig: 466.714ms
twig: 460.756ms
twig: 470.311ms
twig: 429.305ms
twig: 441.919ms
twig: 420.993ms
twig: 429.014ms
twig: 410.996ms
twig: 409.333ms
twig: 434.281ms

**v0.10.3**
```sh
> local/twig.js   chore/include-performance  i=10; while [ $i -gt 0 ]; do node benchmark/test-07-v0.10.3.js; i=$((i-1)); done
twig: 603.089ms
twig: 565.355ms
twig: 560.796ms
twig: 573.100ms
twig: 616.366ms
twig: 594.517ms
twig: 626.077ms
twig: 575.846ms
twig: 577.535ms
twig: 620.392ms
```

The script used to get these numbers for future reference:
```js
window.TwigTemplates = window.TwigTemplates || {};
if(!window.TwigTemplates["views/project/test_template_1.twig"]) {
    window.TwigTemplates["views/project/test_template_1.twig"] = Twig.twig({ autoescape: true, id: "/templates/get/?name=project/test_template_1.twig", namespaces: {"project":"/templates/get/?name=project"}, data: [{"type":"logic","token":{"type":"Twig.logic.type.include","only":false,"ignoreMissing":false,"stack":[{"type":"Twig.expression.type.string","value":"@project/test_template_2.twig"}]}}] });
    window.TwigTemplates["views/project/test_template_2.twig"] = Twig.twig({ autoescape: true, id: "/templates/get/?name=project/test_template_2.twig", namespaces: {"project":"/templates/get/?name=project"}, data: [] });
}

console.time('twig');
for(var i = 0; i < 100000; i++) {
    window.TwigTemplates["views/project/test_template_1.twig"].render();
}
console.timeEnd('twig');
```

**Comment by DrParanoia** [comment]
@JorgenEvens I am really sorry for not answering for so long, was really busy! The latest changes are awesome! It looks like it's at least 1.5x faster than the old twig (pre async)!!! Please do merge if you don't have any more changes in mind.

**Comment by DrParanoia** [comment]
@JorgenEvens @dave-irvine are you guys here? :D

**Comment by JorgenEvens** [comment]
@DrParanoia @dave-irvine I think this PR is good to go.

**Comment by DrParanoia** [comment]
@dave-irvine Ar you still here? ^^ Ping :D

**Comment by ericmorand** [comment]
I don't know exactly if this is this fix that changed everything, but based on my twing-benchmark tool (https://github.com/ericmorand/twing-benchmark), twig.js 1.12 is more than 4 times(!!!) faster than twig.js 1.10.

I tested both version this morning and here are the results of the benchmark (lower is better):

* 1.10.5: 28.23s
* 1.12.0: **6.33s**

Impressive improvements. Congrats to whoever worked on this.

**Pull request merged**
