### PR TITLE
Make loading and rendering async only

### PR DESCRIPTION
**Pull request by PolyPik**
This commit will make loading a template from a file, local or
remote, asynchronous only.

The only way to have synchronous template loading is to provide a string or
array of compiled tokens to the data attribute of the parameters object
passed to `Twig.twig`.

Addresses #612

### CODE REVIEW

**Comment by willrowe** [comment]
I can take a look at this next week, a bit swamped this week.

**Comment by RobLoach** [comment]
This is some incredible change. Nicely done... Are we changing some of the APIs?

Will the build process adapt this for browsers?

**Comment by PolyPik** [comment]
> This is some incredible change. Nicely done... Are we changing some of the APIs?
> 
> Will the build process adapt this for browsers?

This commit makes rendering a purely asynchronous process, so yes there are public API changes.

As for the build process, all it does right now for the browser build is create a minified version of the server build. I think for an upcoming task we can do a bit better by excluding the fs loader entirely from the browser build.

**Comment by PolyPik** [comment]
@dave-irvine Are these changes acceptable?

**Comment by willrowe** [comment]
@PolyPik I am planning on taking a look over this tomorrow if you would still like me to.

**Comment by PolyPik** [comment]
> @PolyPik I am planning on taking a look over this tomorrow if you would still like me to.

I would like that very much. 

My concern is that I mistranslated certain tests and that the CLI not longer works.

**Comment by willrowe** [comment]
> My concern is that I mistranslated certain tests and that the CLI not longer works.
I'll be sure to double-check that.

**Comment by willrowe** [comment]
I started taking a look over this, but then realized that #628 needs to be reverted.

There's also a lot of issues involved with too many changes being made at once that I'm afraid will cause things to break. I think we need to go back to the drawing board on this and try again with incremental changes instead of one large PR.

A good, simple start would be to just remove the option to render synchronously, then all synchronous-specific code could be removed.

**Comment by PolyPik** [comment]
Closing this PR. These changes will be a part of version 2.0.0.

**Pull request closed without merging**
