### PR TITLE
Change the order of the expression.

### PR DESCRIPTION
**Pull request by chenos**
Although ignore missing not working

```
{% include 'demo.html' ignore missing with {'foo': 'bar'} only %}
```

not

```
{% include ignore missing 'demo.html' with {'foo': 'bar'} only %}

```

### CODE REVIEW

**Comment by dave-irvine** [comment]
We don't bundle src/ in npm, that is for the final package distribution, so if you could revert that, and your change to package.json I can take another look. Thanks!

**Comment by chenos** [comment]
I have restored the package.json and .npmignore

**Comment by dave-irvine** [comment]
Do you think you could add a test case that fails before your changes and works after your changes? This helps us make sure we don't break the thing you fixed in the future!

**Comment by dave-irvine** [comment]
Was fixed in https://github.com/twigjs/twig.js/pull/424

**Pull request closed without merging**
