### PR TITLE
Upgrade to Webpack 4

### PR DESCRIPTION
**Pull request by mortenson**
I just started using Twig.js and wanted to make some updates to `webpack.config.js` when I realized that we're still on Webpack 1! We should upgrade to the latest version, 4, to open us up to new plugins and performance enhancements.

This doesn't improve anything about the build size right now, but the build time has been reduced about a second.

### CODE REVIEW

**Comment by mortenson** [comment]
Tests are failing for Node 4 - we would have to change the minimum supported version of Node to 6.x for this PR to be merged.

Good news is that Node 4 is dropping out of LTS support at the end of this month (https://github.com/nodejs/Release#release-schedule), so there shouldn't be a reason to support it after that date.

**Comment by dave-irvine** [comment]
@mortenson Ping me once 4 is EOL and I'll merge this.

**Comment by mattgrill** [comment]
4.x end of life is today 🎉

**Comment by mortenson** [comment]
@dave-irvine Ping 😉And thanks in advance!

**Pull request merged**
