### PR TITLE
Added support for Twig bitwise operators (b-and, b-or, b-xor)

### PR DESCRIPTION
**Pull request by DrParanoia**

### CODE REVIEW

**Comment by dave-irvine** [comment]
@DrParanoia Looks good to me, but can you please add some tests?

**Comment by DrParanoia** [comment]
Sure ;) Will do it tomorrow

**Comment by DrParanoia** [comment]
I've never wrote any tests before, so I'm sorry if something is not right :D

**Comment by dave-irvine** [comment]
Looks good, thanks very much for your pull request :) 🎉

**Pull request merged**
