### PR TITLE
improve namespaces: support non namespaces path together with namespa…

### LINKED ISSUE #555: namespaces do not work well
I'm using `metalsmith-twig` (wrapper for `twig.js`) for a project and have the following difficulties implementing namespaces.

- `metalsmith-twig` does not support namespaces (so I will make a PR soon)
- When I add support for namespaces to `metalsmith-twig` (locally) my project is broken. Current relative paths (like `_base.twig`) can't be resolved anymore.
- I think I've found the problem in `Twig.path.parsePath` (file: `twig.path.js`), because it returns `file` (string) instead passing it through the `relativePath` function. Probably this works when you're **always** using namespaces for paths and configure the namespace path absolute.

But i think it might be usefull you can use both situations together, so pass always the path string through the `relativePath` function.

```
{# Situation 1: #}
  {% extend '_base.twig' %}

{# Situation 2: #}
  {% include 'namespace::_example.twig' %}
```

So i will suggest to remove line 40 (`return file;`).

### PR DESCRIPTION
**Pull request by boschr**
# Improve namespaces

add support non namespaces path together with namespaces configuration

Fixes #555

### CODE REVIEW

**Comment by willrowe** [comment]
Please add a test to cover the issue you were having in #555.

**Comment by boschr** [comment]
@willrowe fixed your comments and add an `.editorconfig` for more indenting consistency. We also should consider an js/es linter (like `eslint`).

**Comment by boschr** [comment]
@willrowe can you confirm my changes? In case you're waiting for a new commit, i did not, just amend or fixup'ed the rework. Would be really nice if we can merge this soon. Thnx!

**Comment by willrowe** [comment]
- Please remove the `.editorconfig` file, this and linting would be helpful, but I don't want to add anything extra to this PR.
- After that, should be good to go.

**Comment by boschr** [comment]
@willrowe @dave-irvine i already revert the commit where i added the `.editorconfig`. Can we merge this one?

**Comment by willrowe** [comment]
Looks good to me.

**Comment by boschr** [comment]
Thnx guys! Who can release an new version? Would be very nice.

**Comment by boschr** [comment]
@willrowe @dave-irvine any idea when we can release a new version?

**Comment by rutgerbakker95** [comment]
@willrowe @dave-irvine could you guys please release a new version? Thx!!!

**Comment by dave-irvine** [comment]
I'll look into this tonight. It'd be great if someone could work on some CI/CD to make the task easier, right now its a real pain to generate releases!

**Comment by dave-irvine** [comment]
@boschr @rutgerbakker95 1.12.0 released

**Pull request merged**
