### PR TITLE
search for block within grandparents too

### LINKED ISSUE #694: Use of parent() is broken in a case of intermediate template in inheritance chain
Twig.js v1.14.0 breaks use of `parent()` function in a case if templates inheritance chain includes template that does not have a block that is referenced by `parent()`.

Here is simplified setup to reproduce issue:

package.json
```json
{
  "name": "twig-block-issue",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "twig": "1.14.0"
  }
} 
```

index.js
```js
"use strict";

const Twig = require('twig');

Twig.renderFile('./a.twig', {}, (err, html) => {
    console.log(html);
}); 
```

a.twig
```twig
{% extends 'b.twig' %}

{% block content %}
    {{ parent() }}
    <h2>This one came from inherited template</h2>
{% endblock %}
```

b.twig
```twig
{% extends 'c.twig' %} 
```

c.twig
```twig
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
</head>
<body>
{% block content %}
    <h1>This one is from original template</h1>
{% endblock %}
</body>
</html> 
```

I've also published it [as a Gist](https://gist.github.com/FlyingDR/67587623da7a989d4b07bc8d9cd4cc1f) to simplify downloading.

Attempt to rendering this set of templates using twig.js v1.14.0 with `node index.js` produces following error:
```
Error parsing twig template ./a.twig:
TypeError: Cannot read property 'render' of undefined
    at Twig.ParseState.parent (node_modules\twig\twig.js:4609:101)
    at parseParams.then.params (node_modules\twig\twig.js:2672:56)
    at Twig.Thenable.resolvedThen [as then] (node_modules\twig\twig.js:7889:41)
    at Twig.ParseState.parse (node_modules\twig\twig.js:2669:22)
    at Twig.async.forEach (node_modules\twig\twig.js:3187:50)
    at next (node_modules\twig\twig.js:8120:24)
    at Object.Twig.async.forEach (node_modules\twig\twig.js:8131:16)
    at Twig.ParseState.Twig.async.potentiallyAsync (node_modules\twig\twig.js:3169:31)
    at Object.Twig.async.potentiallyAsync (node_modules\twig\twig.js:7834:48)
    at Twig.ParseState.Twig.expression.parse (node_modules\twig\twig.js:3168:27)
```
if version of twig.js is downgraded to 1.13.3 - no error is produced and template renders correctly. 

Issue also vanishes in a case if `a.twig` directly extends `c.twig` without intermediate template or in a case if `b.twig` also contains `{% block content %}`

### PR DESCRIPTION
**Pull request by drzraf**
When looking for a block recursively search for grandparents too.
Fix #694

### CODE REVIEW

**Comment by maxhelias** [comment]
It would also be nice to have a test :)

**Comment by drzraf** [comment]
Sorry, I don't have the time. Feel free to takeover :)

**Comment by willrowe** [comment]
This breaks the existing tests and does not include a test demonstrating the bug it is trying to fix.

**Comment by drzraf** [comment]
Closing abruptly a PR that intent to fix **confirmed**, **explained** and **referenced** bug [#694] won't help improve the software.
You can't  reasonably expect contributors to double/triple/... their time to get the testsuite green.
_Everyone_ is **not** a maintainer, and _everyone_ does not have the same involvement into mocha/quality-insurance/...

**Pull request closed without merging**
