### PR TITLE
Revamp Blocks System

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by RobLoach** [comment]
@willrowe Looks like some conflicts. @owzim You resolved these before? Mind sending a PR? Thanks!

**Comment by willrowe** [comment]
If I have time this week I'll take a look at this.

**Comment by willrowe** [comment]
Just a heads up, I'm planning on doing this tomorrow.

**Comment by RobLoach** [comment]
@willrowe Looking forward to it! Was starting to clean up the source to a common standard, but will hold off on that until this is brought in. Thanks a lot!

**Pull request merged**
