### PR TITLE
XO Updates

### PR DESCRIPTION
**Pull request by PolyPik**
Prior Travis builds were failing due to `package-lock.json` not including `xo`. I took this as an opportunity to not just include the dependency in `package-lock.json` but to also regenerate the lock file from scratch.

### CODE REVIEW

**Comment by PolyPik** [comment]
Okay the

**Comment by PolyPik** [comment]
Okay the tests can now run again, so the previous issue is resolved. But now that xo is working the builds are failing due to the many style and format violations.

@RobLoach should we enforce camelcase?

**Comment by RobLoach** [comment]
All that xo recommends is valid, if we want to adopt xo for syntax checking. I believe our webpack build brings things back to es5 for browser compatability.... Right?

**Comment by PolyPik** [comment]
Webpack by itself doesn't offer transpilation.

For transpiling to ES5, we will need to use the [babel-loader](https://github.com/babel/babel-loader).

**Comment by PolyPik** [comment]
These commits will de-linted the files checked by XO, but only to the extent that errors are no longer being given off. The files still have several warnings that have yet to be resolved.

**Comment by willrowe** [comment]
This needs to be reverted. Usage of `const` and `let` cannot be included until we have some kind of transpiling setup. See #471 where this has been addressed this before.

I'm not very clear on what exactly this PR was originally meant to do, can you explain @PolyPik?

**Comment by PolyPik** [comment]
This PR was meant to add a de-linter to the project to help enforce a consistent coding style and format.

**Comment by willrowe** [comment]
Thanks for clearing that up. Seeing as this breaks browser compatibility, we should probably just remove the `xo` check in `posttest` for right now in addition to reverting this PR so that Travis will not fail. What do you think @RobLoach?

**Comment by PolyPik** [comment]
Is there any reason we couldn't just add babel-loader to our webpack.config?

If the issue is that ES6 code is not being transpiled, then we should add a transpiler instead throwing away these changes.

**Comment by willrowe** [comment]
I would rather have the transpiler in place before making these changes and not have to rush in choosing one right now. This could possibly hold up the v2.0.0 release as well, so since it's just code style and not changing any functionality or fixing any bugs, I would like to revert and revisit later.

**Comment by PolyPik** [comment]
So will this revert go about? Will it involve `git push --force` or will it involve making a new commit that simply sets the state of the repo to that of an older commit?

**Comment by RobLoach** [comment]
Could we move the transpiler in place? May be less work to add the transpiler than revert, and re-revert the change.

**Comment by willrowe** [comment]
If someone has time to put together a PR for adding a transpiler, that would work. The order of things is not ideal, but at this point it's probably fine since no release has been made since these changes.

Sorry for jumping to revert so quickly, I kind of panicked when I saw the changes since I missed this PR initially.

**Pull request merged**
